# Generated by Django 6.0 on 2025-12-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='is_multi_secton',
            new_name='is_multi_section',
        ),
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
