# Generated by Django 6.0 on 2025-12-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0002_rename_is_multi_secton_form_is_multi_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldtype',
            old_name='defauld_validations',
            new_name='default_validations',
        ),
    ]
